name: GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - uses: mymindstorm/setup-emsdk@v9
      
      - name: Add Emscripten Environmental variables
        run: |
          export EMSDK=$(which emcc | sed 's:[^/]*$::')
          export EMSDK_NODE=$EMSDK../../node/$(ls $EMSDK../../node)

      - name: Configure CMake
        run: emcmake cmake
          -DCMAKE_TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
          -DCMAKE_CROSSCOMPILING_EMULATOR=$EMSDK_NODE/node
          -DCMAKE_BUILD_TYPE=Release
          -H${{github.workspace}}
          -B${{github.workspace}}/build/cache
          -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${{github.workspace}}/build/deploy
          -G "Unix Makefiles"
          -DCMAKE_CXX_FLAGS="--shell-file ${{github.workspace}}/src/emscripten_shell.html"
          -DEMSCRIPTEN=1

      - name: Build
        run: cmake --build ${{github.workspace}}/build/cache

      - name: Rename HTML file
        run: mv ${{ github.workspace }}/build/deploy/Identity.html ${{ github.workspace }}/build/deploy/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ${{github.workspace}}/build/deploy
