name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v9
      
      - name: Add Emscripten Environmental variables
        run: |
          echo "EMSDK=$(dirname $(which emcc))" >> $GITHUB_ENV
          echo "EMSDK_NODE=$(dirname $(which emcc))/../node/$(ls $(dirname $(which emcc))/../node)" >> $GITHUB_ENV
          echo "source $(dirname $(which emcc))/emsdk_env.sh" >> $GITHUB_ENV

      - name: Configure CMake
        run: |
          emcmake cmake -DCMAKE_TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake \
                -DCMAKE_CROSSCOMPILING_EMULATOR=$EMSDK_NODE/node \
                -DCMAKE_BUILD_TYPE=Release \
                -H${{ github.workspace }} \
                -B${{ github.workspace }}/build/cache \
                -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${{ github.workspace }}/build/deploy \
                -G "Unix Makefiles"

      - name: Build
        run: cmake --build ${{ github.workspace }}/build/cache

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/build/deploy
